### ISSUE TITLE
create stwebapi template

### ISSUE THREAD

**Issue by ccheetham** [steeltoeoss-incubator/DotNetNewTemplates#6]
template can be used running: `dotnet new stwebapi`.  

Initial template will have no options and only generate a generic project.  Subsequent feature requests will define template options.

As part of implementation, create initial unit test framework.

**Comment by jkonicki** [comment]
We should identify if we will support other applications types, besides webapi.  

I would rather see the name be `steeltoe` or `steeltoe-webapi` before releasing this.
